# Generated by Django 4.1.1 on 2022-10-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0007_alter_question_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
